repo_url: https://github.com/kattni/mkdocs-po-i18n/

not_in_nav: |
  /index.md

theme:
  name: material
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to system preference

markdown_extensions:
  pymdownx.highlight: {}
  pymdownx.superfences: {}
  pymdownx.blocks.admonition: {}
  toc:
    permalink: true
    title: On this page

plugins:
  search: {}
